### PR TITLE
make dock album image more beautiful 

### PR DESCRIPTION
**Pull request by leavez**
with aspect ratio, round corners, and margins

### CODE REVIEW

**Comment by leavez** [comment]
untitled

**Comment by AnakinMac** [comment]
@leavez Can you resolve the conflicts? Maybe add more screenshots?
@shanzi I think the change is ok,  thoughts?

**Comment by leavez** [comment]
untitled3
untitled2
untitled

**Comment by shanzi** [comment]
@AnakinMac @leavez Great! LGTM

**Comment by shanzi** [comment]
@AnakinMac Considering open write access to more collaborator. What's your thought?

**Pull request merged**
